# gdb.pyi
from typing import Any

class Value:
    def __getitem__(self, key: str) -> 'Value': ...
    def dereference(self) -> 'Value': ...
    def cast(self, typ: 'Type') -> 'Value': ...
    @property
    def type(self) -> 'Type': ...
    @property
    def address(self) -> 'Value': ...
    def __add__(self, other: int) -> "Value": ...
    def __radd__(self, other: int) -> "Value": ...
    def __int__(self) -> int: ...
    def __float__(self) -> float: ...

class Type:
    def target(self) -> "Type": ...
    def strip_typedefs(self) -> 'Type': ...
    @property
    def fields(self) -> Any: ...
    ...

pretty_printers: list = []


# noinspection PyPep8Naming
class error(Exception):
    ...
